<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class DemoDataSeeder extends Seeder
{
    public function run()
    {
        // ⚠ HATI-HATI:
        // Ini akan menghapus semua data di tabel users & products.
        // Pakai di environment development / fresh install saja.
        $this->db->table('users')->truncate();
        $this->db->table('products')->truncate();

        // ==========================
        // 1. USER: OWNER & KASIR
        // ==========================
        $password = password_hash('password', PASSWORD_DEFAULT);

        $users = [
            [
                'nama'          => 'Owner Toko',
                'username'      => 'owner',
                'password_hash' => $password,
                'role'          => 'owner',
                // 'created_at'  => date('Y-m-d H:i:s'), // boleh, tapi kolom sudah default CURRENT_TIMESTAMP
            ],
            [
                'nama'          => 'Kasir 1',
                'username'      => 'kasir',
                'password_hash' => $password,
                'role'          => 'kasir',
            ],
        ];

        $this->db->table('users')->insertBatch($users);

        // ==========================
        // 2. PRODUK: ROKOK
        // ==========================
        $rokok = [
            [
                'barcode'    => 'R001',
                'nama'       => 'LA Purple',
                'stok'       => 20,
                'harga_beli' => 28000.0,
                'harga_jual' => 35000,
                'satuan'     => 'bungkus',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'R002',
                'nama'       => 'LA Mango',
                'stok'       => 20,
                'harga_beli' => 28000.0,
                'harga_jual' => 35000,
                'satuan'     => 'bungkus',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'R003',
                'nama'       => 'Tango',
                'stok'       => 20,
                'harga_beli' => 8000.0,
                'harga_jual' => 10000,
                'satuan'     => 'bungkus',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'R004',
                'nama'       => 'Loyal',
                'stok'       => 20,
                'harga_beli' => 8800.0,
                'harga_jual' => 11000,
                'satuan'     => 'bungkus',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'R005',
                'nama'       => 'Sampoerna Avolution',
                'stok'       => 20,
                'harga_beli' => 35200.0,
                'harga_jual' => 44000,
                'satuan'     => 'bungkus',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'R006',
                'nama'       => 'Sampoerna Avolution Menthol',
                'stok'       => 20,
                'harga_beli' => 35200.0,
                'harga_jual' => 44000,
                'satuan'     => 'bungkus',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'R007',
                'nama'       => 'Sampoerna Mild',
                'stok'       => 20,
                'harga_beli' => 28800.0,
                'harga_jual' => 36000,
                'satuan'     => 'bungkus',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'R008',
                'nama'       => 'Sampoerna Mild Menthol',
                'stok'       => 20,
                'harga_beli' => 28800.0,
                'harga_jual' => 36000,
                'satuan'     => 'bungkus',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'R009',
                'nama'       => 'Sampoerna Mild 12',
                'stok'       => 20,
                'harga_beli' => 21600.0,
                'harga_jual' => 27000,
                'satuan'     => 'bungkus',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'R010',
                'nama'       => 'Sampoerna Kretek',
                'stok'       => 20,
                'harga_beli' => 13600.0,
                'harga_jual' => 17000,
                'satuan'     => 'bungkus',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'R011',
                'nama'       => 'Sampoerna Prima',
                'stok'       => 20,
                'harga_beli' => 13600.0,
                'harga_jual' => 17000,
                'satuan'     => 'bungkus',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'R012',
                'nama'       => 'Marlboro Vista',
                'stok'       => 20,
                'harga_beli' => 28000.0,
                'harga_jual' => 35000,
                'satuan'     => 'bungkus',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'R013',
                'nama'       => 'Marlboro Filter Black 12',
                'stok'       => 20,
                'harga_beli' => 20000.0,
                'harga_jual' => 25000,
                'satuan'     => 'bungkus',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'R014',
                'nama'       => 'Marlboro Filter Black 16',
                'stok'       => 20,
                'harga_beli' => 26400.0,
                'harga_jual' => 33000,
                'satuan'     => 'bungkus',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'R015',
                'nama'       => 'Marlboro Filter Black 20',
                'stok'       => 20,
                'harga_beli' => 32000.0,
                'harga_jual' => 40000,
                'satuan'     => 'bungkus',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'R016',
                'nama'       => 'Camel Ungu 12',
                'stok'       => 20,
                'harga_beli' => 16800.0,
                'harga_jual' => 21000,
                'satuan'     => 'bungkus',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'R017',
                'nama'       => 'Villaz',
                'stok'       => 20,
                'harga_beli' => 8800.0,
                'harga_jual' => 11000,
                'satuan'     => 'bungkus',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'R018',
                'nama'       => 'Mustang',
                'stok'       => 20,
                'harga_beli' => 13600.0,
                'harga_jual' => 17000,
                'satuan'     => 'bungkus',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'R019',
                'nama'       => 'Djarum Coklat Extra',
                'stok'       => 20,
                'harga_beli' => 13600.0,
                'harga_jual' => 17000,
                'satuan'     => 'bungkus',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'R020',
                'nama'       => 'Dunhill Hitam 12',
                'stok'       => 20,
                'harga_beli' => 18400.0,
                'harga_jual' => 23000,
                'satuan'     => 'bungkus',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'R021',
                'nama'       => 'Dunhill Hitam 16',
                'stok'       => 20,
                'harga_beli' => 24800.0,
                'harga_jual' => 31000,
                'satuan'     => 'bungkus',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'R022',
                'nama'       => 'Dunhill Putih 16',
                'stok'       => 20,
                'harga_beli' => 24800.0,
                'harga_jual' => 31000,
                'satuan'     => 'bungkus',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'R023',
                'nama'       => 'Dunhill Putih 20',
                'stok'       => 20,
                'harga_beli' => 31200.0,
                'harga_jual' => 39000,
                'satuan'     => 'bungkus',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'R024',
                'nama'       => 'Dji Sam Soe',
                'stok'       => 20,
                'harga_beli' => 16800.0,
                'harga_jual' => 21000,
                'satuan'     => 'bungkus',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'R025',
                'nama'       => 'Dji Sam Soe Premium',
                'stok'       => 20,
                'harga_beli' => 16800.0,
                'harga_jual' => 21000,
                'satuan'     => 'bungkus',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'R026',
                'nama'       => 'Surya 12',
                'stok'       => 20,
                'harga_beli' => 21600.0,
                'harga_jual' => 27000,
                'satuan'     => 'bungkus',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'R027',
                'nama'       => 'Surya 16',
                'stok'       => 20,
                'harga_beli' => 28800.0,
                'harga_jual' => 36000,
                'satuan'     => 'bungkus',
                'gambar'     => null,
            ],
        ];

        // ==========================
        // 3. PRODUK: SEMBAKO
        // ==========================
        $sembako = [
            [
                'barcode'    => 'S001',
                'nama'       => 'Indomie',
                'stok'       => 50,
                'harga_beli' => 2800.0,
                'harga_jual' => 3500,
                'satuan'     => 'pcs',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'S002',
                'nama'       => 'Indomie Jumbo',
                'stok'       => 50,
                'harga_beli' => 3200.0,
                'harga_jual' => 4000,
                'satuan'     => 'pcs',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'S003',
                'nama'       => 'Mie Sedap',
                'stok'       => 50,
                'harga_beli' => 2400.0,
                'harga_jual' => 3000,
                'satuan'     => 'pcs',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'S004',
                'nama'       => 'Mie Sukses',
                'stok'       => 50,
                'harga_beli' => 3200.0,
                'harga_jual' => 4000,
                'satuan'     => 'pcs',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'S005',
                'nama'       => 'Sarimi',
                'stok'       => 50,
                'harga_beli' => 3200.0,
                'harga_jual' => 4000,
                'satuan'     => 'pcs',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'S006',
                'nama'       => 'Intermie',
                'stok'       => 50,
                'harga_beli' => 1200.0,
                'harga_jual' => 1500,
                'satuan'     => 'pcs',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'S007',
                'nama'       => 'Pop Mie',
                'stok'       => 50,
                'harga_beli' => 4400.0,
                'harga_jual' => 5500,
                'satuan'     => 'pcs',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'S008',
                'nama'       => 'Mie Sedap Cup',
                'stok'       => 50,
                'harga_beli' => 4000.0,
                'harga_jual' => 5000,
                'satuan'     => 'pcs',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'S009',
                'nama'       => 'Garam 250gr',
                'stok'       => 30,
                'harga_beli' => 2400.0,
                'harga_jual' => 3000,
                'satuan'     => 'pcs',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'S010',
                'nama'       => 'Garam 1kg',
                'stok'       => 30,
                'harga_beli' => 8000.0,
                'harga_jual' => 10000,
                'satuan'     => 'pcs',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'S011',
                'nama'       => 'Masako 8,5gr',
                'stok'       => 100,
                'harga_beli' => 400.0,
                'harga_jual' => 500,
                'satuan'     => 'pcs',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'S012',
                'nama'       => 'Royco 8,5gr',
                'stok'       => 100,
                'harga_beli' => 400.0,
                'harga_jual' => 500,
                'satuan'     => 'pcs',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'S013',
                'nama'       => 'Beras Harumas per kg',
                'stok'       => 20,
                'harga_beli' => 13600.0,
                'harga_jual' => 17000,
                'satuan'     => 'kg',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'S014',
                'nama'       => 'Beras Ayam Penyet per kg',
                'stok'       => 20,
                'harga_beli' => 12000.0,
                'harga_jual' => 15000,
                'satuan'     => 'kg',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'S015',
                'nama'       => 'Beras Kepri Raya per kg',
                'stok'       => 20,
                'harga_beli' => 12000.0,
                'harga_jual' => 15000,
                'satuan'     => 'kg',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'S016',
                'nama'       => 'Beras Minang Jaya per kg',
                'stok'       => 20,
                'harga_beli' => 12000.0,
                'harga_jual' => 15000,
                'satuan'     => 'kg',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'S017',
                'nama'       => 'Telur perbutir',
                'stok'       => 200,
                'harga_beli' => 1600.0,
                'harga_jual' => 2000,
                'satuan'     => 'butir',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'S018',
                'nama'       => 'Gula 1/4kg',
                'stok'       => 30,
                'harga_beli' => 3200.0,
                'harga_jual' => 4000,
                'satuan'     => 'pcs',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'S019',
                'nama'       => 'Gula 1/2kg',
                'stok'       => 30,
                'harga_beli' => 6400.0,
                'harga_jual' => 8000,
                'satuan'     => 'pcs',
                'gambar'     => null,
            ],
            [
                'barcode'    => 'S020',
                'nama'       => 'Gula 1kg',
                'stok'       => 30,
                'harga_beli' => 12800.0,
                'harga_jual' => 16000,
                'satuan'     => 'pcs',
                'gambar'     => null,
            ],
        ];

        $this->db->table('products')->insertBatch(array_merge($rokok, $sembako));
    }
}
